version: "3"
services:
  db:
    build:
      context: .
    container_name: postgres-autobackup
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    ports:
      - '5432:5432' #database 
    networks:
      - jng_network
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  jng_network: