version: "3"
services:
  db:
    build:
      context: ./postgres
    container_name: postgres-autobackup
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    ports:
      - '5432:5432' #database 
    networks:
      - jng_network
    volumes: 
      - db:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    depends_on:
       - db
    container_name: postgres-autobackup-directus
    restart: always
    environment:
      - KEY=${DIRECTUS_KEY}
      - SECRET=${DIRECTUS_SECRET}
      - DB_CLIENT=pg
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DBNAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_EMAIL=${DIRECTUS_EMAIL}
      - ADMIN_PASSWORD=${DIRECTUS_PW}
      - CORS_ORIGIN="*"
      - CORS_ENABLED="true"
    ports:
        - "8055:8055"
    networks:
      - jng_network

volumes:
  db:
    driver: local

networks:
  jng_network: